# Generated by Django 5.1.6 on 2025-02-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='influencer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='influencer',
            name='content_types',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='collaboration_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='socialmediaaccount',
            name='followers_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
